Add Binder link to the README.md
osscar-org/widget-bandsplot pull request #23
Opened 2022-09-05 14:09 UTC by dou-du

* Add the Binder try link to the README.md, which is useful for checking.

2022-09-05 14:18 UTC, unkcpz requested changes
Thanks @dou-du, there still the confliction of the PR, can you first fix that? And I add some comments on the changes, please have a look.

2022-09-05 14:20 UTC, unkcpz commented
I tried the binder link and it still does not show the figure, I assume you didn't fix that correct?

2022-09-05 14:34 UTC, dou-du commented on example/bandsplot-example.ipynb
> +      },
Yes, I just clean it.

2022-09-05 14:36 UTC, dou-du commented on binder/environment.yml
> +  # - ipywidgets
It is better to have two, since environment.yml is for binder and requirements.txt is mainly for dokku app. They may need to have different packages.

2022-09-05 14:39 UTC, dou-du commented on js/lib/example.js
>          value: 'Hello World!'
This version is for the model and view in the backbone.js. It is not necessary to update it every time. I just have some problem to make the widget working in the Jupyter and think the version number is the problem. But it is not the source of the issue.

2022-09-05 15:06 UTC, unkcpz commented on js/lib/example.js
>          value: 'Hello World!'
If it is not the source of the issue, can you set it back? it is confuse the version keep the same as the widget version. Or we should?

2022-09-05 15:14 UTC, dou-du commented
> @dou-du Please request my review when it is ready. thanks.

It should be working now. This is not the same as dokku app. The binder opens the notebook in a JupyterLab. You need to run the code to get the figure, which is also easier for you to test the widget.

2022-09-05 15:21 UTC, unkcpz commented on binder/environment.yml
> +  # - ipywidgets
I still think it is not a good idea to keep two files if most of the dependencies need to keep the same. Is there a way in CI to check if this file is compatible with the requirements.txt or the `setup.cfg` if we gonna support modernized module setup in the future? Maybe @csadorf has experience with how to do this?

2022-09-05 15:25 UTC, unkcpz requested changes
Hi @dou-du, all good, and the example in binder show the widget. Only a minor request that if the version change of the model and view is not needed, can you revert it back?

2022-09-05 15:25 UTC, unkcpz commented on js/lib/example.js
>          value: 'Hello World!'
Hi @dou-du, can you explain what this version is about? If this change is not needed, I think it is better to revert it back, no?

2022-09-05 15:30 UTC, csadorf commented on binder/environment.yml
> +  # - ipywidgets
No, to my knowledge there is no trivial way of checking consistency. I've implemented [such a function](https://github.com/aiidateam/aiida-core/blob/182824050af4efa347108dd9bdcc66a97507be35/utils/dependency_management.py#L171) for aiida-core that provides this kind of consistency check, but I would think that this is overkill in this case.

To my understanding dokku [might be able to build from a conda environment.yml file](https://elements.heroku.com/buildpacks/heroku-python/conda-buildpack), however the docs state that it is actually recommended to use a Docker image in that case. So we could simply provide a small Dockerfile to use the environment.yml file for both binder and dokku. I would recommend to simply keep both the environment.yml and the requirements.txt file for now.

2022-09-06 01:32 UTC, dou-du commented
> Hi @dou-du, all good, and the example in binder show the widget. Only a minor request that if the version change of the model and view is not needed, can you revert it back?

Yes, I changed it back.

2022-09-07 22:13 UTC, unkcpz commented
Hi @dou-du, as we discussed in aiidalab meeting. It still lack of the example in README so users can easily get the sense how to use the widget without open the binder link. I suggest you implement it here. But I am okay if you want to do it with another PR, just let me know. 

Please update the bulletin items of https://github.com/osscar-org/widget-bandsplot/issues/21 to track the updated status of this.

2022-09-07 22:15 UTC, unkcpz approved these changes
LGTM 🚀 Thanks! @dou-du 

Please [squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits) to clean up the commits message. I'll let you decide whether you want to update the README with minimal demo in this PR or anther.

2022-09-09 02:56 UTC, merged